<?php
/**
 * @file
 * Provides a permission for each category assigned to a Forena report.
 * @license https://www.gnu.org/licenses/gpl-2.0.html GPL v2 or later
 */

/**
 * Implementation of hook_permission
 */
function forena_permission_permission() {
  module_load_include('inc', 'forena', 'forena.common');
  $perms = array();
  $result = forena_get_user_reports('');
  foreach ($result as $category => $reports) {
    $perms['forena category ' . htmlspecialchars($category)] = array('title' => t('View Forena Reports of ') . '<i>' . htmlspecialchars($category) . '</i>',
        'description' => t('In your SQL block, use') . ' "--ACCESS=forena category ' . htmlspecialchars($category) . '"');
  }
  return $perms;
}