<?php
/**
 * @file
 * Provides a permission for each category assigned to a Forena report.
 * @license https://www.gnu.org/licenses/gpl-2.0.html GPL v2 or later
 */

/**
 * Implementation of hook_permission
 */
function forena_permission_permission() {
  $perms = array();
  $result = db_query('SELECT distinct category FROM {forena_reports}');
  foreach ($result as $row) {
    $perms['forena category ' . htmlspecialchars($row->category)] = array('title' => t('View Forena Reports of ') . '<i>' . htmlspecialchars($row->category) . '</i>',
    	'description' => t('In your SQL block, use') . ' "--ACCESS=forena category ' . htmlspecialchars($row->category) . '"');
  }
  return $perms;
}
